name: taskatlas_flutter
description: "TaskAtlas — Offline-first Tasks, Notes & Habits"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.0.0

  # State management
  flutter_riverpod: ^2.5.1

  # Database & persistence
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path: ^1.8.3
  path_provider: ^2.1.1

  # Networking
  dio: ^5.4.0

  # Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Internationalization
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.2

  # Temporarily commented out due to build issues
  # flutter_local_notifications: ^16.3.3
  # camera: ^0.10.5+9
  # geolocator: ^11.0.0
  # permission_handler: ^11.3.1
  # workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.0

  # Testing
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
